#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# AMOS Database Setup
# Creates the amos database, a dedicated DB user, applies
# the schema, seeds initial data, and writes credentials
# to .env so the app picks them up automatically.
#
# Usage:  bash db/setup.sh            (prompts for MariaDB root password)
#         bash db/setup.sh --reset    (drops and recreates everything)
# ─────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"

DB_NAME="amos"
DB_USER="amos"
DB_SOCKET="/tmp/mysql.sock"
SCHEMA_FILE="$SCRIPT_DIR/schema.sql"
SEED_SCRIPT="$SCRIPT_DIR/seed.py"
PYTHON="${PROJECT_ROOT}/.venv/bin/python3"

RESET=false
if [[ "${1:-}" == "--reset" ]]; then
    RESET=true
fi

# ── Helpers ─────────────────────────────────────────────
info()  { printf "\033[1;34m▸ %s\033[0m\n" "$1"; }
ok()    { printf "\033[1;32m✔ %s\033[0m\n" "$1"; }
warn()  { printf "\033[1;33m⚠ %s\033[0m\n" "$1"; }
fail()  { printf "\033[1;31m✗ %s\033[0m\n" "$1"; exit 1; }

# ── Pre-flight checks ──────────────────────────────────
command -v mariadb >/dev/null 2>&1 || command -v mysql >/dev/null 2>&1 || \
    fail "Neither mariadb nor mysql CLI found. Install MariaDB first."

MYSQL_CLI="mysql"
command -v mariadb >/dev/null 2>&1 && MYSQL_CLI="mariadb"

[[ -f "$SCHEMA_FILE" ]] || fail "Schema file not found: $SCHEMA_FILE"
[[ -f "$SEED_SCRIPT" ]] || fail "Seed script not found: $SEED_SCRIPT"

if [[ ! -f "$PYTHON" ]]; then
    warn "Virtual env not found at $PYTHON — falling back to system python3"
    PYTHON="python3"
fi

# ── MariaDB root credentials ───────────────────────────
info "MariaDB root access"
echo "  Enter the MariaDB root password (leave blank if none):"
read -rsp "  Root password: " ROOT_PASS
echo

MYSQL_ARGS=(-u root)
if [[ -n "$ROOT_PASS" ]]; then
    MYSQL_ARGS+=(-p"$ROOT_PASS")
fi
if [[ -S "$DB_SOCKET" ]]; then
    MYSQL_ARGS+=(--socket="$DB_SOCKET")
fi

# Verify root access
$MYSQL_CLI "${MYSQL_ARGS[@]}" -e "SELECT 1;" >/dev/null 2>&1 || \
    fail "Cannot connect to MariaDB as root. Check password / socket."
ok "Connected to MariaDB"

# ── Generate random password for amos user ──────────────
AMOS_PASS="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24)"

# ── Reset mode ──────────────────────────────────────────
if $RESET; then
    warn "Reset mode — dropping database and user"
    $MYSQL_CLI "${MYSQL_ARGS[@]}" -e "DROP DATABASE IF EXISTS \`$DB_NAME\`;"
    $MYSQL_CLI "${MYSQL_ARGS[@]}" -e "DROP USER IF EXISTS '$DB_USER'@'localhost';"
fi

# ── Create database ────────────────────────────────────
info "Creating database '$DB_NAME'"
$MYSQL_CLI "${MYSQL_ARGS[@]}" -e "CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
ok "Database '$DB_NAME' ready"

# ── Create user ─────────────────────────────────────────
info "Creating user '$DB_USER'@'localhost'"
# Drop and re-create to ensure password is current
$MYSQL_CLI "${MYSQL_ARGS[@]}" -e "DROP USER IF EXISTS '$DB_USER'@'localhost';"
$MYSQL_CLI "${MYSQL_ARGS[@]}" -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$AMOS_PASS';"
$MYSQL_CLI "${MYSQL_ARGS[@]}" -e "GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';"
$MYSQL_CLI "${MYSQL_ARGS[@]}" -e "FLUSH PRIVILEGES;"
ok "User '$DB_USER' created with generated password"

# ── Apply schema ────────────────────────────────────────
info "Applying schema from $(basename "$SCHEMA_FILE")"
$MYSQL_CLI "${MYSQL_ARGS[@]}" "$DB_NAME" < "$SCHEMA_FILE"
ok "Schema applied ($(grep -c 'CREATE TABLE' "$SCHEMA_FILE") tables)"

# ── Write .env ──────────────────────────────────────────
info "Writing credentials to .env"

# Preserve existing .env content (minus any old DB vars)
if [[ -f "$ENV_FILE" ]]; then
    EXISTING=$(grep -v '^AMOS_DB_' "$ENV_FILE" || true)
else
    EXISTING=""
    # Seed from .env.example if available
    if [[ -f "$PROJECT_ROOT/.env.example" ]]; then
        EXISTING=$(cat "$PROJECT_ROOT/.env.example")
    fi
fi

cat > "$ENV_FILE" <<EOF
$EXISTING

# Database (generated by db/setup.sh)
AMOS_DB_USER=$DB_USER
AMOS_DB_PASS=$AMOS_PASS
AMOS_DB_NAME=$DB_NAME
AMOS_DB_HOST=localhost
AMOS_DB_PORT=3306
AMOS_DB_SOCKET=$DB_SOCKET
EOF

ok ".env updated"

# ── Seed data ───────────────────────────────────────────
info "Seeding initial data"
AMOS_DB_USER="$DB_USER" AMOS_DB_PASS="$AMOS_PASS" AMOS_DB_NAME="$DB_NAME" \
    AMOS_DB_SOCKET="$DB_SOCKET" $PYTHON "$SEED_SCRIPT"
ok "Seed complete"

# ── Summary ─────────────────────────────────────────────
echo
echo "════════════════════════════════════════════"
echo "  AMOS Database Ready"
echo "  Database : $DB_NAME"
echo "  User     : $DB_USER"
echo "  Socket   : $DB_SOCKET"
echo "  .env     : updated with credentials"
echo "════════════════════════════════════════════"
echo
echo "  Start AMOS:  python3 web/app.py"
echo
